### ISSUE TITLE
Version number in POM?

### ISSUE THREAD

**Issue by keilw** [eclipse-ee4j/soteria#214]
I'm wondering, if the version number `1.1-b01-SNAPSHOT` isn't an overkill?

IMO 1.1-SNAPSHOT may be enough if 1.1 was the next possible Soteria release.
The "b01" doesn't really show up anywhere in [Eclipse Version Numbering](https://wiki.eclipse.org/Version_Numbering) (which may be slightly influenced by RCP and plugins but generally stands for all projects) Milestone builds like  "M1" or "m01" which we also had in Soteria pre 1.0 are common at Eclipse but usually as a release tag only, see [Eclipse Collections 9.2.0.M1](https://github.com/eclipse/eclipse-collections/releases/tag/9.2.0.M1). The master branch has` 10.0.0-SNAPSHOT` in its POM, so either `1.1-SNAPSHOT` or `1.1.0-SNAPSHOT` sounds more appropriate here.

Plus the current master of [Jersey](https://github.com/eclipse-ee4j/jersey/blob/master/pom.xml) also says `2.28-SNAPSHOT` not "2.28-b01-SNAPSHOT".

**Comment by ggam** [comment]
I think that beta sufix was put there by Oracle during the release process, with no apparent reason. I'm +1 with using just SNAPSHOT
