### ISSUE TITLE
New Wildfly versions in README?

### ISSUE THREAD

**Issue by keilw** [eclipse-ee4j/soteria#215]
I used JSR 375 demos like https://github.com/keilw/javaee-soteria-jwt on Wildfly 11 or 12 Final, so shouldn't the statement that Soteria runs fully on Wildfly 10 be extended to 11 and 12 as well?
Or are there known issues with either of those preventing such statement?

**Comment by ggam** [comment]
AFAIK WildFly 12 (beta) is using Soteria as their JSR 375 implementation so it should work fine. But I think we can wait a bit to get CI working again and ensure compatibilities?

**Comment by keilw** [comment]
No worries, I saw Wildfly 13 has just gone Final, almost impossible to catch up in those readme files ;-D

**Comment by keilw** [comment]
Superceded by #304
