### ISSUE TITLE
Unable to use Soteria with a <distributable/> application

### ISSUE THREAD

**Issue by mnriem** [eclipse-ee4j/soteria#218]
Because the "org.glassfish.soteria.original.request" session attribute is non-serializable Soteria cannot be used in a web application marked as distributable.

**Comment by mnriem** [comment]
Also see issue #9

**Comment by arjantijms** [comment]
Thanks for the report. This is a "known" issue indeed, but there wasn't a direct uhm issue for it yet.

This is one of the MUST fix things for Soteria 1.1, maybe should have a spec clarification as well.

**Comment by keilw** [comment]
Btw, would it also make sense to mark the target version separately using the Milestone feature of GitHub here? Otherwise with likely high release-cycles (at least twice a year) those "Soteria_X_Y_mustfix" labels may soon grow out of control.

**Comment by arjantijms** [comment]
Indeed, that would be the official target for an issue. The green extra label is just an extra hint, or priority.

**Comment by keilw** [comment]
There is a milestone 1.1 now. The other one "Futures" does not hurt either. It can be a placeholder when the exact release for a fix is not yet sure.

**Comment by ggam** [comment]
Looking at the `RequestData` class (https://github.com/eclipse-ee4j/soteria/blob/b4854a4051a45557f1804313d20ececdec4ab106/impl/src/main/java/org/glassfish/soteria/servlet/RequestData.java), seems like everything is serializable but the `Map` and `List` objects. Would it be enough to add `Serializable` interface to the class and force the use of `ArrayList` and `Hashmap`?
