### ISSUE TITLE
Build CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/soteria#228]
This task is for creating a basic build CI/CD pipeline for this project on Eclipse infrastructure. More information is here: https://ci.eclipse.org/.

**Comment by wesleyegberto** [comment]
Hi Dmitry

May I take this one? I'll be happy to help on it.
If I don't advance within a week I will report to someone else to try.

**Comment by ggam** [comment]
@weilk I think you haven't yet started on this?

**Comment by m0mus** [comment]
@keilw Werner, we have a volunteer here. Since you are working on JMS it makes sense giving this task to him. Please answer.

**Comment by keilw** [comment]
I remember Steven said, Payara volunteered for the projects it (@arjantijms ) leeds, so no problem if they do it or allow someone else.

**Comment by m0mus** [comment]
@arjantijms, do you have any objections to @wesleyegberto helping with this task?

**Comment by arjantijms** [comment]
@m0mus I don't have any objections of course ;) I did setup a very similar pipeline before for Soteria, and still have to do it for Mojarra, but as with everything time is always an issue. So the more help the better. Thx!

**Comment by wesleyegberto** [comment]
I will start then =)
Thank you

**Comment by m0mus** [comment]
@arjantijms, can you please look on this: https://bugs.eclipse.org/bugs/show_bug.cgi?id=538265
@eclipsewebmaster requires +1 from you on the bug. Please handle it.

**Comment by arjantijms** [comment]
@m0mus 

I interpreted it as something that's not needed, and was just requested since @wesleyegberto didn't see the other way.

There's an outstanding question:

```
I've volunteer myself to setup the pipeline, what do I need to do to get the permission on this instance?
```

It looks like the answer for that is needed first.

**Comment by arjantijms** [comment]
Project CI environment has been requested:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=538676

The other bug can be closed, as it requests the shared instance.

**Comment by ggam** [comment]
@wesleyegberto any progress on this? I don't have much Jenkins experience but I might try to take this if everyone else is busy on other stuff.

**Comment by m0mus** [comment]
@arjantijms Sorry, there are too many GitHub notifications. I've just seen your question. I tried to solve it with Eclipse many times. There was no suitable solution offered. Currently there is no easy way for non-committers to do CI/CD work.

**Comment by arjantijms** [comment]
I've requested all the JIPPs, and most should be there now. Will work on this at the latest next week. Apologies for everyone who tried to help, it's indeed not easy for non-committers.

**Comment by arjantijms** [comment]
Job created and runs. Branch https://github.com/eclipse-ee4j/soteria/tree/1.0.1. created by soteria bot.

**Comment by ggam** [comment]
Awesome! Thanks for the hard work!
