### ISSUE TITLE
Recommitting whole repository = "commit stealing"

### ISSUE THREAD

**Issue by Quix0r** [eclipse-ee4j/soteria#234]
According to the [main repository](https://github.com/javaee/security-soteria) (this one is based on) this repository is a continuation. As under normal conditions, like here seems to be, you normally maintain the full commit history to give kudos/credits to the very committing authors.

But this is not the case here (as it seems?). Even if a single commit would be re-committed (means committed again but under new author) it is internet-widely considered as "commit-stealing" as the committer id (author's name and email address) has been replaced with a new one giving the new one kudos/credits for "his" work.

Please rethink this and may fork + re-commit (it can be done!) and force-push the repository. Please also note that this means no harm to you, just a consideration of given giving kudos to the rightful author.

**Comment by bshannon** [comment]
We're not able to preserve the history for legal reasons.  Sorry.

**Comment by Quix0r** [comment]
Okay, sad to hear that a legal reason is behind this.
