### ISSUE TITLE
Integrate to GlassFish

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/soteria#240]
- [ ] Integrate to Eclipse GlassFish
- [ ] Pass all CTS/TCK tests

#235 must be finished before starting working on this task.

security-api, jacc-api and jaspic-api should be integrated as part of Soteria integration.

**Comment by arjantijms** [comment]
#235 is done

**Comment by lukasj** [comment]
see https://github.com/eclipse-ee4j/glassfish/pull/22654
