### ISSUE TITLE
How to implement jaspic on wildly?

### ISSUE THREAD

**Issue by sekaijin** [eclipse-ee4j/soteria#241]
I am looking to implemented jaspic in a JEE application under wildfly.

I based on soteria /test/app-securitycontext-customprincipal

But this is done for tests, not for a real application.
I do not understand in the code what comes under the test and what I have to implement.

If I run the tests of the soteria project with the profile wildfly no problems.

but if I want to create a war that I deploy on my server, I do not understand.

for example there is in the code a jboss-web.xml with "jaspitest" but "jaspitest" is present nowhere.

I thought to find it on my wildfly server. but there is nothing. how to create it? it is not indicated.

Is there a tutorial that explains step by step what to do.

all the examples being for tests I can not find anything on a real implementation.

thank

**Comment by arjantijms** [comment]
Regarding the Jboss-web.xml file, see: https://arjan-tijms.omnifaces.org/2015/08/activating-jaspic-in-jboss-wildfly.html

A very, very, unfortunate matter is that historically JASPIC needed to be activated on JBoss/WildFly. I'm not sure what the current state is in WildFly. Have to retest it soon.

The tests are real mini applications in their own right too. You can use them to build your own app from.

For a larger example app (tested on WildFly and Payara) using EE security, see https://github.com/javaeekickoff/java-ee-kickoff-app

**Comment by sekaijin** [comment]
thank you very very much.
I will study that.

A+JYT
