### ISSUE TITLE
javax.security.enterprise.authentication.mechanism.http.RememberMe annotation does not have cookieNameExpression

### ISSUE THREAD

**Issue by haducloc** [eclipse-ee4j/soteria#253]
RememberMe annotation has:

- isRememberMe & isRememberMeExpression
- cookieMaxAgeSeconds & cookieMaxAgeSecondsExpression
- cookieSecureOnly & cookieSecureOnlyExpression
- cookieHttpOnly & cookieHttpOnlyExpression

AND

cookieName BUT NO cookieNameExpression.

Please add cookieNameExpression so we can provide cookieName at runtime!

**Comment by ggam** [comment]
Hi @haducloc. All string attributes support expressions. The `*Expression` properties were added in companion to non-string attributes to allow expressions on them.

You can have a look at the code to verify `cookieName` indeed handles expressions: https://github.com/eclipse-ee4j/soteria/blob/master/impl/src/main/java/org/glassfish/soteria/cdi/RememberMeAnnotationLiteral.java#L92

**Comment by haducloc** [comment]
Thank you! I close the issue.
