### ISSUE TITLE
Provide SPI for Servlet container integration

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/soteria#263]
The Jakarta Security spec states the following:

> "Section 14.4, item 18, of [SERVLET40] describes requirements for supporting BASIC and FORM authentication via the web.xml login-config element. This specification requires that implementations of BASIC and FORM be made available as HttpAuthenticationMechanism CDI beans. The servlet container is NOT REQUIRED to implement separate and independent mechanisms to satisfy each requirement. Instead, the container MAY choose to provide a single mechanism, for each of BASIC and FORM, that meets the requirements of both specifications; i.e., an implementation that can be configured via login-config, but which is also made available as an HttpAuthenticationMechanism if the application uses the corresponding annotation."

Soteria does not make it particularly easy to realise this option, especially given the requirement imposed by the spec that a Jakarta EE authentication mechanism overrides a login-config definition in web.xml.

In order to make this easier, one option would be for the web container to make the results from parsing web.xml (which is not natively accessibly to a CDI extension) available to Soteria.

**Comment by rdebusscher** [comment]
@arjantijms Good idea, but I was wondering what happens if there are multiple applications deployed (EAR)?

According to your initial PR, this `WebXmlLoginConfig` is used in the CDI extension. Is web.xml already parsed at that point or is also a change on the platform level needed to explicitly defined the order in which submodules are initialized?

**Comment by arjantijms** [comment]
> According to your initial PR, this WebXmlLoginConfig is used in the CDI extension. Is web.xml already parsed at that point or is also a change on the platform level needed to explicitly defined the order in which submodules are initialized?

Good question! The web.xml can be parsed a little later than the moment where the SPI is set, since the integrator can supply an implementation that lazy loads the web.xml data when needed.

There's multiple options here. For instance, at the moment the SPI is installed in Soteria web.xml is not parsed yet, but the integrator knows it will be at the time the CDI extension for Soteria is initialised. The SPI implementation can then just grab it. Alternatively, if web.xml is not parsed yet when the Soteria extension is called (for instance, because the integrator's implementation doesn't have such guarantees), the SPI implementation can parse it on the fly.

As @ggam asked, I created an example of this for Piranha. This used a third option where the integrator does have all data readily available.

A Soreria pre-CDI init is installed here:

https://github.com/manorrock/piranha/blob/master/micro/src/main/java/com/manorrock/piranha/micro/PiranhaServerDeployer.java#L139

Which then copies the data needed to the default installation:

https://github.com/manorrock/piranha/blob/master/piranha-security-soteria/src/main/java/com/manorrock/piranha/security/soteria/SoteriaPreCDIInitializer.java#L65
