### ISSUE TITLE
Add authentication mechanism for OpenID Connect

### ISSUE THREAD

**Issue by rdebusscher** [eclipse-ee4j/soteria#308]
Implementation of the new spec item https://github.com/eclipse-ee4j/security-api/issues/183

**Comment by arjantijms** [comment]
Big +1 for this.

As a historical note, we had this in scope for Jakarta Security 1.0 back then (together with JWT), but as we ran out of time very little was done for it. Jan Beernink (of OmniFaces) did create this that somewhat comes close:

https://github.com/omnifaces/soteria-google-oauth-client

Payara has created this one:

https://github.com/payara/ecosystem-security-connectors/tree/master/oauth2

and this one:

https://github.com/payara/ecosystem-security-connectors/tree/master/openid

**Comment by arjantijms** [comment]
Just a small ping here, we have about a month left to get this in ;)

**Comment by rdebusscher** [comment]
I was playing around to see if we could make the OpenIdConnect implementation extensible in a way we can keep the additional features we have in Payara.

But decided now to keep our own implementation (also due to backward compatibility reasons) and thus porting a version of the code to Soteria.

**Comment by rdebusscher** [comment]
@arjantijms See draft version of OpenId Connect implementation

https://github.com/eclipse-ee4j/soteria/pull/313

**Comment by rdebusscher** [comment]
@arjantijms I plan to add some more tests around OpenIdConnect by the end of the week.

**Comment by rdebusscher** [comment]
closed by merging in https://github.com/eclipse-ee4j/soteria/pull/313
