### ISSUE TITLE
Soteria 4.0.0-M3 uses automatic module name

### ISSUE THREAD

**Issue by mnriem** [eclipse-ee4j/soteria#386]
Soteria 4.0.0-M3 uses automatic module name, please consider delivering a proper module-info.java file. 

If so desired I can create a PR for this

**Comment by mnriem** [comment]
Can you also do another milestone release?

**Comment by mnriem** [comment]
@arjantijms Was a release done?

**Comment by arjantijms** [comment]
> Can you also do another milestone release?

It would be a micro release (4.0.1). 4.0.0 was already released.

**Comment by mnriem** [comment]
Go for it!
